url: http://bigpicturelabs.io
baseurl: ""

# Site settings
title: 빅픽처랩(주) bigpicturelabs inc.
email: contact@bigpicturelabs.com
description: "Official website for bigpicturelabs inc."

# Team names, titles and social links
people:
  - name: 금창섭
    pic: 1
    position: CEO
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/changsup-keum-20922626/
    career:
      - title: 빅픽처랩 대표
      - title: ETRI 신뢰서비스플랫폼연구실장
      - title: SW공학소사이어티/CDE 학회 이사
      - title: 블록체인 강연 100회 이상
    education:
      - title: KAIST 공학박사 (전산학)
      - title: 카네기멜론대학교 공학석사
  - name: 안휘
    pic: 5
    position: CTO
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/hwiahn/
      - title: github
        url: https://github.com/byron1st
    career:
      - title: 블록체인 개발팀장
      - title: 오픈소스 it-chain 아키텍트
    education:
      - title: 카네기멜론대학교 공학석사
      - title: KAIST 학사 (전산학)
  - name: 이재준
    pic: 2
    position: 개발팀장
    social:
      - title: github
        url: https://github.com/jaejun1ee
    career:
      - title: AI 개발팀장
      - title: 딥러닝 기반 코드 변경 추천 시스템
      - title: Tu Berlin 방문연구원
    education:
      - title: KAIST 공학석사 (전산학)
      - title: 한양대학교 학사 (전산학)

advisor:
  - name: 김정호
    pic: 3
    position: Advisor
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/정호-김-614700a5/
    career:
      - title: 명지대학교 교수 (SW 아키텍처)
      - title: 제이유컨설팅 대표
    education:
      - title: KAIST 공학박사 (전산학)
      - title: 카네기멜론대학교 공학석사
  - name: 이선아
    pic: 6
    position: Advisor
    social:
      - title: google-plus
        url: https://sites.google.com/site/saleese/
    career:
      - title: 경상대학교 교수 (데이터 분석, AI)
      - title: 네브마인 대표
    education:
      - title: KAIST 공학박사 (전산학)
      - title: 카네기멜론대학교 공학석사

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/bigpicturelabs
  - title: facebook
    url: http://facebook.com/bigpicturelabs

# Postal address (add as many lines as necessary)
address:
  - line: 3동 302호
  - line: (34047) 대전광역시 유성구 유성대로1689번길 70 (전민동, KT대덕2연구센타)

# Build settings
markdown: kramdown
permalink: pretty
