url: http://bigpicturelabs.io
baseurl: ""

# Site settings
title: 빅픽처랩(주) bigpicturelabs inc.
email: contact@bigpicturelabs.com
description: "Official website for bigpicturelabs inc."


# Team names, titles and social links
people:
- name: Keum, Changsup
  pic: 1
  position: CEO, Chief SW Architect
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/changsup-keum-20922626/
  career:
    - title: ETRI, Head of Trust Communication Platform R&D Center
    - title: Ministry of Science and ICT, committee for blockchain
    - title: Software Engineer, society director
    - title: Computer Science(PhD), KAIST
    - title: CSE(M.A), Carnegie Mellon University

- name: Hwi Ahn
  pic: 2
  position: CTO, SW Architect
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/hwiahn/
    - title: github
      url: https://github.com/byron1st
  career:
    - title: Computer Science(PhD candidate), KAIST
    - title: MSIT-SE(M.A), Carnegie Mellon University

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/bigpicturelabs
  - title: facebook
    url: http://bigpicturelabs.co.kr
  - title: medium
    url:
  - title: steemit
    url:

# Postal address (add as many lines as necessary)
address:
  - line: ETRI 11동 207호
  - line: (34129) 대전광역시 유성구 가정로 218

# Build settings
markdown: kramdown
permalink: pretty